version: '2'
services:
  web:
    build: .
    container_name: hw01
    environment:
      - STAGE=$STAGE
      - PG=$PG
      - DEBUG=$DEBUG
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn hello_world.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - "8000:8000"